#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --no-input --clear
python manage.py migrate

/usr/local/bin/gunicorn config.wsgi:application --bind 0.0.0.0:8000
