version: '3'

volumes:
  {{ cookiecutter.project_slug }}_postgres_data: {}
  {{ cookiecutter.project_slug }}_postgres_data_backups: {}
  {{ cookiecutter.project_slug }}_static_data: {}
  {{ cookiecutter.project_slug }}_media_data: {}

services:
  nginx:
    image: "${NGINX_IMAGE}"
    container_name: nginx_{{ cookiecutter.project_slug }}
    depends_on:
      - django
    volumes:
      - {{ cookiecutter.project_slug }}_static_data:/usr/src/app/static
      - {{ cookiecutter.project_slug }}_media_data:/usr/src/app/media
    ports:
      - "8888:80"
    restart: always

  django:
    image: "${DJANGO_IMAGE}"
    container_name: django_{{ cookiecutter.project_slug }}
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    command: /start
    volumes:
      - {{ cookiecutter.project_slug }}_static_data:/app/staticfiles
      - {{ cookiecutter.project_slug }}_media_data:/app/app/media
    expose:
      - 8000
    restart: always

  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: postgres_{{ cookiecutter.project_slug }}
    volumes:
      - {{ cookiecutter.project_slug }}_postgres_data:/var/lib/postgresql/data:Z
      - {{ cookiecutter.project_slug }}_postgres_data_backups:/backups:z
    env_file:
      - ./.env
    restart: always

  redis:
    image: redis:6
    container_name: redis_{{ cookiecutter.project_slug }}
    restart: always
