version: '3'

volumes:
  lawncare_postgres_data: {}
  lawncare_postgres_data_backups: {}
  lawncare_static_data: {}
  lawncare_media_data: {}

services:
  nginx:
    image: "${NGINX_IMAGE}"
    container_name: nginx_lawncare
    depends_on:
      - django
    volumes:
      - lawncare_static_data:/usr/src/app/static
      - lawncare_media_data:/usr/src/app/media
    ports:
      - "8888:80"
    restart: always

  django:
    image: "${DJANGO_IMAGE}"
    container_name: django_lawncare
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    command: /start
    volumes:
      - lawncare_static_data:/app/staticfiles
      - lawncare_media_data:/app/app/media
    expose:
      - 8000
    restart: always

  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: postgres_lawncare
    volumes:
      - lawncare_postgres_data:/var/lib/postgresql/data:Z
      - lawncare_postgres_data_backups:/backups:z
    env_file:
      - ./.env
    restart: always

  redis:
    image: redis:6
    container_name: redis_lawncare
    restart: always
